---
linear_simulation:
    seed: 42
    n_samples: 2_500
    kernel_dim: 29
    n_experiments: 25
    sweep_samples: 25
    methods:
        - ERM
        - DA+ERM
        - DA+UIV-CV
        - DA+UIV-LCV
        - DA+UIV-CC
        - DA+IV
        - IRM
        - ICP
        - DRO
        - RICE
        - V-REx
        - MM-REx
    augmentations:
        - translate

optical_device:
    seed: 42
    n_samples: 1_000
    methods:
        - ERM
        - DA+ERM
        - DA+UIV-CV
        - DA+UIV-LCV
        - DA+UIV-CC
        - DA+IV
        - IRM
        - ICP
        - DRO
        - RICE
        - V-REx
        - MM-REx
    augmentations:
        - gaussian-noise

colored_mnist:
    seed: 42
    num_seeds: 10
    n_samples: 60_000
    methods:
        - ERM
        - DA+ERM
        - DA+UIV-CV
        - DA+UIV-LCV
        - DA+IV
        - IRM
        - DRO
        - RICE
        - V-REx
        - MM-REx
    augmentations:
        - jitter > translate

hyperparameters:
    sgd:
        lr: 0.01
        batch: 256
        epochs: 16
    cv:
        folds: 5            # k-fold CV number of folds
        frac: 0.2           # vanilla CV test set fraction
        samples: 10         # number of samples for random search
        n_jobs: -1           # number of jobs to run in parallel for hyperparam search
